server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: PostUploadSection
          uri: http://localhost:8081
          predicates:
            - Path=/indexInfos/**, 
        - id: StreamingSection
          uri: http://localhost:8082
          predicates:
            - Path=/streamInfos/**, 
        - id: UploadSection(Core)
          uri: http://localhost:8083
          predicates:
            - Path=/files/**, 
        - id: DashBoardSection
          uri: http://localhost:8084
          predicates:
            - Path=, 
        - id: notification
          uri: http://localhost:8085
          predicates:
            - Path=, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: PostUploadSection
          uri: http://postUploadSection:8080
          predicates:
            - Path=/indexInfos/**, 
        - id: StreamingSection
          uri: http://streamingSection:8080
          predicates:
            - Path=/streamInfos/**, 
        - id: UploadSection(Core)
          uri: http://uploadSectionCore:8080
          predicates:
            - Path=/files/**, 
        - id: DashBoardSection
          uri: http://dashBoardSection:8080
          predicates:
            - Path=, 
        - id: notification
          uri: http://notification:8080
          predicates:
            - Path=, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
