apiVersion: v1
kind: Service
metadata:
  name: UploadSection(Core)
  labels:
    app: UploadSection(Core)
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: UploadSection(Core)