---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: PostUploadSection
  labels:
    app: PostUploadSection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: PostUploadSection
  template:
    metadata:
      labels:
        app: PostUploadSection
    spec:
      containers:
        - name: PostUploadSection
          image: username/PostUploadSection:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: StreamingSection
  labels:
    app: StreamingSection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: StreamingSection
  template:
    metadata:
      labels:
        app: StreamingSection
    spec:
      containers:
        - name: StreamingSection
          image: username/StreamingSection:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: UploadSection(Core)
  labels:
    app: UploadSection(Core)
spec:
  replicas: 1
  selector:
    matchLabels:
      app: UploadSection(Core)
  template:
    metadata:
      labels:
        app: UploadSection(Core)
    spec:
      containers:
        - name: UploadSection(Core)
          image: username/UploadSection(Core):latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: DashBoardSection
  labels:
    app: DashBoardSection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: DashBoardSection
  template:
    metadata:
      labels:
        app: DashBoardSection
    spec:
      containers:
        - name: DashBoardSection
          image: username/DashBoardSection:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  labels:
    app: notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: username/notification:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: PostUploadSection
  labels:
    app: PostUploadSection
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: PostUploadSection


---


apiVersion: v1
kind: Service
metadata:
  name: StreamingSection
  labels:
    app: StreamingSection
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: StreamingSection


---


apiVersion: v1
kind: Service
metadata:
  name: UploadSection(Core)
  labels:
    app: UploadSection(Core)
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: UploadSection(Core)


---


apiVersion: v1
kind: Service
metadata:
  name: DashBoardSection
  labels:
    app: DashBoardSection
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: DashBoardSection


---


apiVersion: v1
kind: Service
metadata:
  name: notification
  labels:
    app: notification
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: notification

